name: Test coverage

on:
  push:
    branches:
      - 'main'
    tags-ignore:
      - '**'

jobs:

  collect_coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Grant execute permission for gradlew
        shell: bash
        run: chmod +x gradlew
      - name: Get coverage
        shell: bash
        run: ./gradlew koverReport
      - name: Parse coverage
        id: parse_coverage
        uses: stevenleadbeater/kover-report-parser-action@0.0.1
